// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"ExcludeMaterialGuard","status":true,"description":"未使用素材削除ガードプラグイン","parameters":{"画像素材":"[\"animations/Cure1\",\"sv_actors/Actor2_8\"]","音声素材":"[\"se/Coin\"]","音声素材2":"[\"Bell2\"]","素材3":"[\"img/enemies/Actor2_5\"]"}}
];
